-- vim.cmd([[
--   augroup Yank
--   autocmd!
--   autocmd TextYankPost * :call system('/mnt/c/windows/system32/clip.exe ', @")
--   augroup END
-- ]])

-- vim.g.wsl_clipboard_command = "win32yank.exe -i --crlf"

-- vim.g.clipboard = {
-- 	name = "WslClipboard",
-- 	copy = {
-- 		["*"] = "/mnt/c/Windows/System32/clip.exe",
-- 		["+"] = "/mnt/c/Windows/System32/clip.exe",
-- 	},
-- 	paste = {
-- 		["+"] = "/mnt/c/Windows/System32/clip.exe",
-- 		["*"] = "/mnt/c/Windows/System32/clip.exe",
-- 	},
-- 	cache_enabled = 0,
-- }

-- local clip = "/mnt/c/Windows/System32/clip.exe"
-- if executable(clip) then
-- 	vim.cmd([[
--     augroup Yank
--     autocmd!
--     autocmd TextYankPost * :call system('/mnt/c/Windows/System32/clip.exe ', @")
--     augroup END
--   ]])
-- end
